# schedule
day1: Thursdays
time1: 1 PM - 4 PM
loc1: <strong>BA-1170</strong> - <em>Bahen Centre for Information Technology</em>

# day2: Fridays
# time2: 5 PM - 7 PM
# loc2: <strong>BA-1180</strong> - <em>Bahen Centre for Information Technology</em>

dayTut: Fridays
timeTut: 5 PM - 6 PM
locTut: <strong>BA-1130</strong> - <em>Bahen Centre for Information Technology</em>

start_date: September 10, 2025
# start_description: 

start_dateTut: September 18, 2025

dayOffice: Thursdays 
timeOffice: 4 PM - 5 PM

# Site settings
course_name: Reinforcement Learning
course_description: "This course develops fundamental understanding and hands-on skills in reinforcement learning. The course is designed in three major parts: Part I gives the students a warm welcome by taking them through the basic definitions and fundamental concepts. Part II explains fundamental reinforcement learning methods by touching the key model-based and model-free techniques and providing deep understanding of these methods. Part III explores deep reinforcement learning, where deep neural networks are employed to efficiently approximate the developed techniques in Part II. In this part, we take a look into several algorithms, such as deep Q-learning, policy gradient methods, e.g., trust-region and proximal policy optimization algorithms, and actor-critic methods."
course_semester: "Fall 2026"


assgn_mark: 40%
assgn_desc: "4 assignment sets"
assgn_txt: "There will be 4 sets of assignments. Roughly speaking, the first one goes through fundamentals of reinforcement learning. The second assignment gets more serious in terms of implementation and develops your knowledge on tabular reinforcement learning methods. The last two assignments gives you a chance to implement some mini-projects on Deep Reinforcement Learning. The assignments will count for 40% of your final mark."

exam_mark: 30%
exam_desc: "2 in-term exams"
exam_txt: "We have two in-term exams in this semester. The exams are on <em>Friday, October 23</em> and <em>Friday, December 4.</em> Each exam will ask two questions similar to what you have seen in assignments, tutorials, and practice questions shared with you. The exam evaluates the understanding of fundamental concepts."

project_mark: 30%
project_desc: "open-ended projects"
project_txt: "An open-ended project is to be completed through semester. Students work in groups. The final projects will be presented in the second week of December."


baseurl: "/rl-utoronto" # the subpath of your site, e.g. /blog/
url: "https://bereyhi-courses.github.io/" # the base hostname & protocol for your site

schoolname: "University of Toronto"
schoolurl: "https://www.ece.utoronto.ca"
personal_page: "bereyhi.com"

address: |
    The Edward S. Rogers Sr. Department of Electrical and Computer Engineering
    University of Toronto

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

minima:
  include_css:
    - /assets/css/custom.css

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include:
  - assets
  - _images
  - _css

exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false

defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
